소셜로그인, 토큰 갱신 기능 추가
Read-bird/readbird-be pull request #7
Opened 2023-12-12 15:49 UTC by seungE95

### PR 타입
-[] 기능 추가

### 반영 브랜치
dev-login -> dev

### 변경 사항
구글 소셜 로그인, 토큰 갱신 기능을 추가했습니다.

### 테스트 결과
![스크린샷 2023-12-13 004538](https://github.com/Read-bird/readbird-be/assets/77827700/d01585fc-3dae-4f71-a895-e04469e42376)
![스크린샷 2023-12-13 004025](https://github.com/Read-bird/readbird-be/assets/77827700/10823a42-79b1-47cd-a867-255843972adf)
![스크린샷 2023-12-13 004357](https://github.com/Read-bird/readbird-be/assets/77827700/af07532c-3c13-49ac-a380-f028937d7a8c)
![스크린샷 2023-12-13 004503](https://github.com/Read-bird/readbird-be/assets/77827700/9031b1cc-c219-4d15-bbf0-ba61c7fffd0d)

2023-12-13 02:22 UTC, kimmand0o0 requested changes
고생하셨습니다! 리뷰 확인 부탁드립니다!

2023-12-13 02:22 UTC, kimmand0o0 commented on src/architecture/controllers/user.controller.ts
> +    });
토큰은 headers에 저장해서 보내주면 좋을 것 같습니다. body는 탈취 위험이 높습니다.

2023-12-13 02:22 UTC, kimmand0o0 commented on src/architecture/controllers/user.controller.ts
> +    const kakaoToken: any = headers?.split("Bearer ")[1];
Bearer가 없이 토큰이 올 경우 에러가 날 것 같은 데 혹시 어떻게 처리가 되나요?

2023-12-13 02:22 UTC, kimmand0o0 commented on src/architecture/repositories/user.repository.ts
> +        // const userSelect = await Users.sequelize!.query(sql);
사용하지 않는 코드라면 삭제하는 게 좋을 것 같습니다.

2023-12-13 02:22 UTC, kimmand0o0 commented on src/architecture/repositories/user.repository.ts
> +        console.log("\nuserSelect ::: " + JSON.stringify(userSelect));
값을 확인하기 위한 콘솔 로그들이 보이네용, 배포환경에서 필요가 없다면 삭제하는 것이 좋아보입니다.

2023-12-13 02:22 UTC, kimmand0o0 commented on src/architecture/repositories/user.repository.ts
> +        return false;
회원가입에 실패할 경우 false값이 나오는 데 혹시 에러처리가 되는 부분이 있을까요?

2023-12-13 02:22 UTC, kimmand0o0 commented on src/architecture/services/user.service.ts
> +    //if (!email || !nickName) throw new Error("KEY_ERROR");
값이 없는 경우 에러 발생이 예상되는 데 주석처리 되어있네요! 혹시 어떻게 처리되나요?

2023-12-13 02:22 UTC, kimmand0o0 commented on src/jwt/jwt-util.ts
> +            return false;
try catch 문이 중복으로 사용 된 것으롭 보입니다.
이런 경우 가장 외부를 감싸고 있는 try catch 만으로도 작동을 하는 것으로 알고있습니다.

2023-12-13 02:22 UTC, kimmand0o0 commented on src/jwt/jwt-util.ts
> +            algorithm: "HS256",
알고리즘은 환경변수로 선언하지 않아도 괜찮을까요?

2023-12-13 02:22 UTC, kimmand0o0 commented on src/routers/index.ts
> +import userRouter from "./user.route";
이부분 통일하는 게 좋아보이네요!
제가 수정하도록 하겠습니다 :)

2023-12-13 03:34 UTC, seungE95 commented on src/architecture/controllers/user.controller.ts
> +    });
그렇군요!

2023-12-13 03:37 UTC, seungE95 commented on src/routers/index.ts
> +import userRouter from "./user.route";
답글 달아 주신거 전부 확인 했고 수정해서 다시 올리도록 하겠습니다 감사합니다!

2023-12-14 08:00 UTC, kimmand0o0 approved these changes
고생하셨습니다!

2023-12-14 09:41 UTC, merged